In [2]:
import numpy as np

nullVector = np.zeros(10)                                   # Create a null vector of size 10
nullVector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
nullVector2 = np.zeros(10)                                  # Create a null vector of size 10 but the fifth value which is 1
nullVector2[4] = 1
nullVector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
vector = np.arange(10, 50)                                  # Create a vector with values ranging from 10 to 49
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
matrix = np.arange(0, 9).reshape((3, 3))                    # Create a 3x3 matrix with values ranging from 0 to 8
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
array = np.random.rand(10, 10)                              # Create a 10x10 array with random values and find the minimum and maximum values
array

array([[0.26471157, 0.37590525, 0.19788309, 0.29221176, 0.46508405,
        0.01337582, 0.99631898, 0.89278136, 0.23781355, 0.12995257],
       [0.70433472, 0.02322415, 0.19350062, 0.09412111, 0.49952698,
        0.24599332, 0.36063131, 0.06678914, 0.63575474, 0.84843636],
       [0.81176079, 0.32706043, 0.88184296, 0.3527651 , 0.30193079,
        0.8317919 , 0.01454097, 0.84669624, 0.77367184, 0.19433273],
       [0.10389361, 0.59340375, 0.99882396, 0.45205145, 0.77257415,
        0.57357293, 0.69015228, 0.41873387, 0.22389834, 0.34283814],
       [0.21606377, 0.83239859, 0.47325129, 0.38747637, 0.1899322 ,
        0.52912762, 0.75834433, 0.43258176, 0.53356072, 0.47377883],
       [0.08612106, 0.22961431, 0.10963977, 0.55445488, 0.3750144 ,
        0.8544758 , 0.09210681, 0.83049398, 0.06150206, 0.71888196],
       [0.30526276, 0.64793208, 0.48606602, 0.16850684, 0.10989245,
        0.38492091, 0.81451715, 0.83627156, 0.72388035, 0.34337386],
       [0.56332413, 0.83715666, 0.2574804

In [10]:
array.min()

0.011629791894124386

In [11]:
array.max()

0.9988239559658747

In [12]:
array2d = np.ones((5,5))                                    # Create a 2d array with 1 on the border and 0 inside
array2d[1:-1,1:-1] = 0
array2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
multiply = np.random.random((5,3))@np.random.random((3,2))  # Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
multiply

array([[0.19785333, 0.71924043],
       [0.61248504, 0.65191369],
       [0.75104511, 1.07381244],
       [0.68984657, 0.75748572],
       [0.95268335, 1.05941941]])